(()=>{
'use strict';
const $=id=>document.getElementById(id), clamp=(v,a,b)=>Math.min(b,Math.max(a,v)), num=(id,d=0)=>{const v=Number($(id).value);return Number.isFinite(v)?v:d};
const MONTHS=['January','February','March','April','May','June','July','August','September','October','November','December'];
const COLORS=['#2a78d6','#1baf7a','#a576d4','#d48a54','#5c8eaa','#b16b86'];
const DEFAULT=[
 {years:5,monthlyInvest:500,mortgageExtra:0,mortgageFreq:'monthly',annualBonus:0,bonusDest:'invest'},
 {years:5,monthlyInvest:750,mortgageExtra:200,mortgageFreq:'monthly',annualBonus:2000,bonusDest:'split'},
 {years:10,monthlyInvest:1000,mortgageExtra:3000,mortgageFreq:'yearly',annualBonus:4000,bonusDest:'invest'},
 {years:5,monthlyInvest:750,mortgageExtra:500,mortgageFreq:'monthly',annualBonus:3000,bonusDest:'mortgage'},
 {years:5,monthlyInvest:500,mortgageExtra:0,mortgageFreq:'monthly',annualBonus:0,bonusDest:'invest'},
 {years:5,monthlyInvest:500,mortgageExtra:0,mortgageFreq:'monthly',annualBonus:0,bonusDest:'invest'}];
let phases=DEFAULT.map(x=>({...x})), chart;
function fmt(v){const n=Math.round(v||0);return '€'+n.toLocaleString('nl-NL')} function fmtSigned(v){return (v<0?'−':'+')+fmt(Math.abs(v))}
function initMonths(){['startMonth','bonusMonth'].forEach(id=>{const el=$(id);MONTHS.forEach((m,i)=>{const o=document.createElement('option');o.value=i+1;o.textContent=m;el.appendChild(o)})});$('startMonth').value='1';$('bonusMonth').value='12'}
function renderPhases(){const count=clamp(num('phaseCount',3),1,6),root=$('phaseList');root.innerHTML='';let cursor=new Date(Date.UTC(num('startYear',2026),num('startMonth',1)-1,1));for(let i=0;i<count;i++){const p=phases[i];const months=Math.round(p.years*12);const end=new Date(Date.UTC(cursor.getUTCFullYear(),cursor.getUTCMonth()+months-1,1));const card=document.createElement('div');card.className='phase-card';card.innerHTML=`<div class="phase-head"><p class="phase-title"><span class="dot" style="background:${COLORS[i]}"></span>Phase ${i+1}</p><p class="phase-period">${MONTHS[cursor.getUTCMonth()].slice(0,3)} ${cursor.getUTCFullYear()} – ${MONTHS[end.getUTCMonth()].slice(0,3)} ${end.getUTCFullYear()}</p></div><div class="phase-fields"><div><label class="mini">Duration, years</label><input data-i="${i}" data-field="years" type="number" min="1" max="30" step="1" value="${p.years}"></div><div><label class="mini">Monthly investment</label><input data-i="${i}" data-field="monthlyInvest" type="number" min="0" step="50" value="${p.monthlyInvest}"></div><div><label class="mini">Planned extra mortgage repayment</label><input data-i="${i}" data-field="mortgageExtra" type="number" min="0" step="50" value="${p.mortgageExtra}"></div><div><label class="mini">Repayment frequency</label><select data-i="${i}" data-field="mortgageFreq"><option value="monthly" ${p.mortgageFreq==='monthly'?'selected':''}>Monthly</option><option value="yearly" ${p.mortgageFreq==='yearly'?'selected':''}>Yearly</option></select></div><div><label class="mini">Annual bonus / lump sum</label><input data-i="${i}" data-field="annualBonus" type="number" min="0" step="100" value="${p.annualBonus}"></div><div><label class="mini">Bonus allocation</label><select data-i="${i}" data-field="bonusDest"><option value="invest" ${p.bonusDest==='invest'?'selected':''}>Invest 100%</option><option value="mortgage" ${p.bonusDest==='mortgage'?'selected':''}>Mortgage 100%</option><option value="split" ${p.bonusDest==='split'?'selected':''}>Split 50 / 50</option></select></div></div>`;root.appendChild(card);cursor=new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth()+1,1))}}
function plan(){const count=clamp(num('phaseCount',3),1,6);return phases.slice(0,count).map(p=>({years:clamp(Number(p.years)||1,1,30),monthlyInvest:Math.max(0,Number(p.monthlyInvest)||0),mortgageExtra:Math.max(0,Number(p.mortgageExtra)||0),mortgageFreq:p.mortgageFreq==='yearly'?'yearly':'monthly',annualBonus:Math.max(0,Number(p.annualBonus)||0),bonusDest:['invest','mortgage','split'].includes(p.bonusDest)?p.bonusDest:'invest'}))}
function deductionRate(){if($('deductionMode').value==='manual')return clamp(num('manualDeduction',37.56),0,60)/100;const income=num('grossIncome',0);return income<=38883?0.3575:0.3756}
function ewf2026(woz){if(woz<=12500)return 0;if(woz<=25000)return woz*.001;if(woz<=50000)return woz*.002;if(woz<=75000)return woz*.0025;if(woz<=1350000)return woz*.0035;return 4725+(woz-1350000)*.0235}
function mortTaxBenefit(interest,months,rate,ewfAnnual,enabled){if(!enabled||months<=0)return 0;const ewf=ewfAnnual*months/12;if(interest>=ewf)return (interest-ewf)*rate;const hillen=.71867;return -(ewf-interest)*(1-hillen)*rate}
function inputs(retOverride,mortTypeOverride){return{p:plan(),startMonth:clamp(num('startMonth',1),1,12),startYear:clamp(num('startYear',2026),2020,2100),startPortfolio:Math.max(0,num('startPortfolio',0)),annualReturn:retOverride??num('annualReturn',7),bonusMonth:clamp(num('bonusMonth',12),1,12),mortBalance:Math.max(0,num('mortBalance',0)),mortRate:clamp(num('mortRate',0),0,20),mortYears:clamp(num('mortYears',1),1,40),mortType:mortTypeOverride||( $('mortType').value==='linear'?'linear':'annuity'),mortTaxEnabled:$('mortTaxEnabled').checked,deductRate:deductionRate(),wozValue:Math.max(0,num('wozValue',0)),box3Mode:$('box3Mode').value,taxPartners:clamp(num('taxPartners',1),1,2),box3PaySource:$('box3PaySource').value,currentTaxRate:clamp(num('currentTaxRate',36),0,100)/100,currentAllowance:Math.max(0,num('currentAllowance',59357)),currentNotional:clamp(num('currentNotional',6),0,30)/100,firstJan1Portfolio:Math.max(0,num('firstJan1Portfolio',0)),futureStart:clamp(num('futureStart',2028),2027,2100),futureTaxRate:clamp(num('futureTaxRate',36),0,100)/100,futureExempt:Math.max(0,num('futureExempt',1800)),futureLossThreshold:Math.max(0,num('futureLossThreshold',500))}}
function regimeForYear(inp,year){if(inp.box3Mode==='none')return'none';if(inp.box3Mode==='current')return'current';if(inp.box3Mode==='future')return'future';return year>=inp.futureStart?'future':'current'}
function simulate(retOverride,forceNoBox3=false,mortTypeOverride=null){const I=inputs(retOverride,mortTypeOverride);if(forceNoBox3)I.box3Mode='none';const im=(I.annualReturn/100)/12, mm=(I.mortRate/100)/12, mortMonths=Math.max(1,Math.round(I.mortYears*12));const initialMort=I.mortBalance, linearPrincipal=initialMort/mortMonths, annPay=mm===0?initialMort/mortMonths:initialMort*mm/(1-Math.pow(1+mm,-mortMonths));let portfolio=I.startPortfolio,invested=I.startPortfolio,mort=initialMort,grossInterest=0,extraPaid=0,scheduledPrincipal=0,box3Tax=0,currentTax=0,futureTax=0,lossCarry=0,payoffDate=null;const schedule=[],series=[],yearBuckets={};let date=new Date(Date.UTC(I.startYear,I.startMonth-1,1)),global=0;
  function bucket(y){if(!yearBuckets[y])yearBuckets[y]={year:y,startPortfolio:null,endBeforeTax:0,marketGain:0,contrib:0,mortInterest:0,mortMonths:0,mortTax:0,box3Tax:0,regime:'none'};return yearBuckets[y]}
  for(const p of I.p){const pMonths=Math.round(p.years*12);for(let pm=0;pm<pMonths;pm++){global++;const y=date.getUTCFullYear(),mo=date.getUTCMonth()+1,b=bucket(y);if(b.startPortfolio===null)b.startPortfolio=portfolio;const growth=portfolio*im;portfolio+=growth;b.marketGain+=growth;
    let investContrib=p.monthlyInvest;let bonusInvest=0,bonusMort=0;if(mo===I.bonusMonth&&p.annualBonus>0){if(p.bonusDest==='invest')bonusInvest=p.annualBonus;else if(p.bonusDest==='mortgage')bonusMort=p.annualBonus;else{bonusInvest=p.annualBonus/2;bonusMort=p.annualBonus/2}}investContrib+=bonusInvest;portfolio+=investContrib;invested+=investContrib;b.contrib+=investContrib;
    let interest=0,principal=0,extra=0,grossScheduled=0,taxReturn=0;if(mort>0){interest=mort*mm;grossInterest+=interest;b.mortInterest+=interest;b.mortMonths++;if(I.mortType==='linear')principal=Math.min(mort,linearPrincipal);else principal=Math.min(mort,Math.max(0,annPay-interest));grossScheduled=interest+principal;mort-=principal;scheduledPrincipal+=principal;if(p.mortgageFreq==='monthly')extra+=p.mortgageExtra;else if(mo===I.bonusMonth)extra+=p.mortgageExtra;extra+=bonusMort;extra=Math.min(mort,Math.max(0,extra));mort-=extra;extraPaid+=extra;taxReturn=mortTaxBenefit(interest,1,I.deductRate,ewf2026(I.wozValue),I.mortTaxEnabled);if(mort<=.005){mort=0;if(!payoffDate)payoffDate=new Date(date)}}
    schedule.push({date:new Date(date),balance:mort,gross:grossScheduled,principal,interest,taxReturn,net:grossScheduled-taxReturn,extra});b.endBeforeTax=portfolio;
    const next=new Date(Date.UTC(y,mo,1));const endOfCalendarYear=next.getUTCFullYear()!==y;const finalMonth=(global===I.p.reduce((s,x)=>s+Math.round(x.years*12),0));if(endOfCalendarYear||finalMonth){const regime=regimeForYear(I,y);b.regime=regime;let tax=0;if(regime==='current'){const jan1Value=(I.startYear===y&&I.startMonth>1)?I.firstJan1Portfolio:Math.max(0,b.startPortfolio||0);const allowance=I.currentAllowance*I.taxPartners;const notionalIncome=Math.max(0,jan1Value-allowance)*I.currentNotional;const notionalTax=notionalIncome*I.currentTaxRate;const actualTax=Math.max(0,b.marketGain)*I.currentTaxRate;tax=Math.min(notionalTax,actualTax);currentTax+=tax}else if(regime==='future'){const exempt=I.futureExempt*I.taxPartners;let result=b.marketGain;if(result<0){lossCarry+=Math.max(0,-result-I.futureLossThreshold)}else{const afterLoss=Math.max(0,result-lossCarry);const usedLoss=Math.min(lossCarry,result);lossCarry-=usedLoss;tax=Math.max(0,afterLoss-exempt)*I.futureTaxRate}futureTax+=tax}b.box3Tax=tax;box3Tax+=tax;if(I.box3PaySource==='portfolio')portfolio=Math.max(0,portfolio-tax);b.endAfterTax=portfolio;series.push({date:new Date(date),portfolio,mort,invested,box3Tax});}
    date=new Date(Date.UTC(y,mo,1));}}
  let mortTax=0;Object.values(yearBuckets).forEach(b=>{b.mortTax=mortTaxBenefit(b.mortInterest,b.mortMonths,I.deductRate,ewf2026(I.wozValue),I.mortTaxEnabled);mortTax+=b.mortTax});const grossScheduledTotal=grossInterest+scheduledPrincipal;const firstScheduled=schedule.length?schedule[0].gross:0;return{...I,portfolio,invested,mort,initialMort,grossInterest,mortTax,netInterest:grossInterest-mortTax,extraPaid,scheduledPrincipal,grossScheduledTotal,firstScheduled,box3Tax,currentTax,futureTax,lossCarry,payoffDate,schedule,series,yearBuckets,horizonMonths:global}}
function updateStats(s){$('sPortfolio').textContent=fmt(s.portfolio);$('sPortfolioSub').textContent=fmt(s.portfolio-s.invested+s.box3Tax)+' gross gains · '+fmt(s.box3Tax)+' tax';$('sInvested').textContent=fmt(s.invested);$('sInvestedSub').textContent='including starting portfolio';$('sBox3').textContent=fmt(s.box3Tax);$('sBox3Sub').textContent=s.box3Mode==='none'?'Box 3 ignored':s.box3PaySource==='portfolio'?'deducted from portfolio':'paid from external cash';$('sMortgage').textContent=fmt(s.mort);$('sMortgageSub').textContent=fmt(s.initialMort-s.mort)+' principal repaid';$('sMortTax').textContent=fmtSigned(s.mortTax);$('sMortTaxSub').textContent=fmt(s.netInterest)+' net interest'}
function updateMortgage(s){$('deductionDisplay').textContent=(s.deductRate*100).toFixed(2)+'%';$('deductionWhy').textContent=$('deductionMode').value==='manual'?'Manual planning rate.':(num('grossIncome',0)>78426?'2026 maximum deduction rate above €78,426.':num('grossIncome',0)>38883?'2026 second-bracket proxy.':'2026 first-bracket proxy.');$('mGrossInterest').textContent=fmt(s.grossInterest);$('mTaxBenefit').textContent=fmtSigned(s.mortTax);$('mNetInterest').textContent=fmt(s.netInterest);$('mPayoff').textContent=s.payoffDate?MONTHS[s.payoffDate.getUTCMonth()].slice(0,3)+' '+s.payoffDate.getUTCFullYear():'Not yet';$('mPayoffSub').textContent=s.payoffDate?'with selected extra repayments':'remaining '+fmt(s.mort)}
function updateMortgageCompare(s){const linear=simulate(s.annualReturn,false,'linear'),annuity=simulate(s.annualReturn,false,'annuity');function card(el,x,label){const active=s.mortType===x.mortType?' active':'';el.className='compare-card'+active;el.innerHTML=`<h3>${label}</h3><p class="tag">${active?'Selected assumption':'Alternative assumption'}</p><div class="metric"><span>First scheduled payment</span><strong>${fmt(x.firstScheduled)}</strong></div><div class="metric"><span>Gross scheduled paid</span><strong>${fmt(x.grossScheduledTotal)}</strong></div><div class="metric"><span>Gross interest</span><strong>${fmt(x.grossInterest)}</strong></div><div class="metric"><span>Estimated tax benefit</span><strong>${fmtSigned(x.mortTax)}</strong></div><div class="metric"><span>Extra repayments</span><strong>${fmt(x.extraPaid)}</strong></div><div class="metric"><span>End balance</span><strong>${fmt(x.mort)}</strong></div>`}card($('linearCompare'),linear,'Linear mortgage');card($('annuityCompare'),annuity,'Annuity mortgage')}
function updateBox3(s){const noTax=simulate(s.annualReturn,true);$('bCurrent').textContent=fmt(s.currentTax);$('bFuture').textContent=fmt(s.futureTax);$('bLoss').textContent=fmt(s.lossCarry);$('bDrag').textContent=fmt(Math.max(0,noTax.portfolio-s.portfolio))}
function updateScenarios(){const root=$('scenarioCards');root.innerHTML='';[[4,'Lower 4%','#9a9a96'],[7,'Illustrative 7%','#2a78d6'],[10,'Higher 10%','#1baf7a']].forEach(([r,l,c])=>{const s=simulate(r),d=document.createElement('div');d.className='scenario';d.style.borderTopColor=c;d.innerHTML=`<p class="lab">${l}</p><p class="val">${fmt(s.portfolio)}</p><p class="sub">${fmt(s.box3Tax)} Box 3 tax · mortgage ${fmt(s.mort)}</p>`;root.appendChild(d)})}
function updateSchedule(s){const body=$('scheduleBody');body.innerHTML='';if($('scheduleView').value==='monthly'){s.schedule.forEach(r=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${MONTHS[r.date.getUTCMonth()].slice(0,3)} ${r.date.getUTCFullYear()}</td><td>${fmt(r.balance)}</td><td>${fmt(r.gross)}</td><td>${fmt(r.principal)}</td><td>${fmt(r.interest)}</td><td>${fmtSigned(r.taxReturn)}</td><td>${fmt(r.net)}</td><td>${fmt(r.extra)}</td>`;body.appendChild(tr)})}else{const y={};s.schedule.forEach(r=>{const yr=r.date.getUTCFullYear();if(!y[yr])y[yr]={balance:0,gross:0,principal:0,interest:0,taxReturn:0,net:0,extra:0};const a=y[yr];a.balance=r.balance;a.gross+=r.gross;a.principal+=r.principal;a.interest+=r.interest;a.taxReturn+=r.taxReturn;a.net+=r.net;a.extra+=r.extra});Object.entries(y).forEach(([yr,r])=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${yr}</td><td>${fmt(r.balance)}</td><td>${fmt(r.gross)}</td><td>${fmt(r.principal)}</td><td>${fmt(r.interest)}</td><td>${fmtSigned(r.taxReturn)}</td><td>${fmt(r.net)}</td><td>${fmt(r.extra)}</td>`;body.appendChild(tr)})}}
function updateChart(s){const labels=s.series.map(x=>MONTHS[x.date.getUTCMonth()].slice(0,3)+' '+x.date.getUTCFullYear()),p=s.series.map(x=>Math.round(x.portfolio)),m=s.series.map(x=>Math.round(x.mort)),i=s.series.map(x=>Math.round(x.invested));if(typeof Chart==='undefined')return;const ctx=$('mainChart').getContext('2d');if(!chart){const dark=matchMedia('(prefers-color-scheme: dark)').matches;chart=new Chart(ctx,{type:'line',data:{labels,datasets:[{label:'Portfolio after Box 3',data:p,borderColor:'#2a78d6',backgroundColor:'rgba(42,120,214,.07)',fill:true,pointRadius:0,borderWidth:2,tension:.25},{label:'Mortgage',data:m,borderColor:'#1baf7a',pointRadius:0,borderWidth:2,tension:.2},{label:'Invested',data:i,borderColor:'#9a9a96',borderDash:[6,4],pointRadius:0,borderWidth:1.5,tension:.2}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>c.dataset.label+': '+fmt(c.raw)}}},scales:{x:{ticks:{autoSkip:true,maxTicksLimit:12,maxRotation:0,color:dark?'#74746f':'#8b8b86'},grid:{display:false}},y:{ticks:{callback:v=>v>=1e6?'€'+(v/1e6).toFixed(1)+'M':v>=1000?'€'+Math.round(v/1000)+'k':'€'+v,color:dark?'#74746f':'#8b8b86'},grid:{color:dark?'rgba(255,255,255,.07)':'rgba(0,0,0,.06)'}}}}})}else{chart.data.labels=labels;chart.data.datasets[0].data=p;chart.data.datasets[1].data=m;chart.data.datasets[2].data=i;chart.update('none')}}
function validate(s){const a=[];if(s.mortTaxEnabled&&s.wozValue===0)a.push('WOZ is €0, so eigenwoningforfait is not offsetting the mortgage deduction.');if(s.box3Mode==='transition')a.push('2027 current Box 3 parameters are not final yet; the calculator deliberately reuses 2026 values as a proxy until the proposed 2028 transition.');if(s.box3Mode==='future'||s.box3Mode==='transition')a.push('The 2028 actual-return regime is proposed legislation, not enacted law as of 1 September 2026.');const el=$('validation');el.textContent=a.join(' ');el.classList.toggle('show',a.length>0)}
function update(){const s=simulate();updateStats(s);updateMortgage(s);updateMortgageCompare(s);updateBox3(s);updateScenarios();updateSchedule(s);updateChart(s);validate(s)}
$('phaseList').addEventListener('input',e=>{const i=Number(e.target.dataset.i),f=e.target.dataset.field;if(!Number.isInteger(i)||!f)return;phases[i][f]=(f==='mortgageFreq'||f==='bonusDest')?e.target.value:Math.max(0,Number(e.target.value)||0);if(f==='years')renderPhases();update()});
$('phaseList').addEventListener('change',e=>{const i=Number(e.target.dataset.i),f=e.target.dataset.field;if(!Number.isInteger(i)||!f)return;phases[i][f]=(f==='mortgageFreq'||f==='bonusDest')?e.target.value:Math.max(0,Number(e.target.value)||0);update()});
document.querySelectorAll('input,select').forEach(el=>{if(el.closest('#phaseList'))return;el.addEventListener('input',()=>{if(el.id==='phaseCount'||el.id==='startMonth'||el.id==='startYear')renderPhases();update()});el.addEventListener('change',()=>{if(el.id==='phaseCount'||el.id==='startMonth'||el.id==='startYear')renderPhases();update()})});
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('tab-'+b.dataset.tab).classList.add('active')}));
initMonths();renderPhases();update();
})();
